# fly.toml app configuration file generated for xe-flux on 2024-08-07T09:21:35-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'xe-flux'
primary_region = 'ord'

[experimental]
  cmd = ['./start.sh']

[build]
  image = 'registry.fly.io/<APP_NAME>:latest'

[env]
  COG_LOG_LEVEL = 'debug'

[[mounts]]
  source = 'flux_cache'
  destination = '/src/flux-cache'
  initial_size = '50G'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[files]]
  guest_path = '/src/start.sh'
  local_path = './start.sh'

[[vm]]
  size = 'performance-2x'
  memory = '16gb'
  cpu_kind = 'performance'
  cpus = 2
